GET http://localhost:5001/api/v1/movies
Content-Type: application/json

### get all cinemas
GET http://localhost:5001/api/v1/cinemas
Content-Type: application/json

### get a cinema by id
GET http://localhost:5001/api/v1/cinemas/5fb93ac9a6edc33f907296b2
Content-Type: application/json

### get movies for the given cinema by cinema id
GET http://localhost:5001/api/v1/movies/5fb93ac9a6edc33f907296b2
Content-Type: application/json

### get payment data INITIAL 
GET http://localhost:5001/api/v1/stripe
Content-Type: application/json

### get booked seats
GET http://localhost:5001/api/v1/bookedSeats/5fa2c884539a6449d84da4e1/5f9ec9f5b0286024eceb5cd8/2020-11-14/18_00
Content-Type: application/json
