GET http://localhost:5001/api/v1/movies
Content-Type: application/json

### get all cinemas
GET http://localhost:5001/api/v1/cinemas
Content-Type: application/json

### get a cinema by id
GET http://localhost:5001/api/v1/cinemas/5f9ef6cfd392b966283408da
Content-Type: application/json