name: backend checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        mongodb-version: [4.2]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install
      - name: seedDb
        env: 
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
        run: npm run seedDb:Test
      - name: test
        env: 
          PORT: 5001
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
        run: npm test
